version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gocognit
    - nestif
    - godox
    - asciicheck
    - godot
    - testpackage

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  funlen:
    lines: 100
    statements: 50
  
  gocognit:
    min-complexity: 20
  
  nestif:
    min-complexity: 4
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  
  dogsled:
    max-blank-identifiers: 2
  
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - nestif
        - mnd
    
    # Exclude known linter issues
    - text: "Use of weak random number generator"
      linters:
        - gosec
    
    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    
    # Exclude certain security checks for test files
    - path: _test\.go
      text: "G404:"
      linters:
        - gosec
    
    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll
    
    # Allow magic numbers in tests
    - path: _test\.go
      linters:
        - mnd